In [2]:
with open("peptides_from_TULIP.txt", "r") as file:
    print(file.readline())

GILGFVFTL



In [2]:
import numpy as np

things = {"hi": "bye", "lie": "fly"}

things_arr = np.array(list(things.items()))
things_arr

array([['hi', 'bye'],
       ['lie', 'fly']], dtype='<U3')

In [40]:
from dataclasses import dataclass


x, y = np.meshgrid((1, 2), (1, 2))
C = np.array(np.transpose((x, y), (2, 1, 0)), dtype=object)
C
print(C)

@dataclass
class A:
    b : tuple

D = np.array(np.ones((2,2)), dtype=object)

for idx, row in enumerate(C):
    for idy, pair in enumerate(row):
        print(C[idx][idy])
        D[idx][idy] = tuple(C[idx][idy])
print(D)    

print(C)

def sumA(a : tuple):
    return sum(a)

vec_sumA = np.vectorize(sumA)

vec_sumA(D)

[[[1 1]
  [1 2]]

 [[2 1]
  [2 2]]]
[1 1]
[1 2]
[2 1]
[2 2]
[[(1, 1) (1, 2)]
 [(2, 1) (2, 2)]]
[[[1 1]
  [1 2]]

 [[2 1]
  [2 2]]]


array([[2, 3],
       [3, 4]])

In [1]:
from sim.discrete_model import get_ones_matrix

a = get_ones_matrix(2,1)
a

array([[1.],
       [1.]])

In [5]:
import numpy as np
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])